services:
  xml-service:
    build: .
    container_name: tp3_xml_service
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "9090:9090"
      - "50051:50051"
    environment:
      - XMLRPC_PORT=9090
      - GRPC_PORT=50051

